# Generated by Django 4.1.7 on 2023-05-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='respons_tec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('CNPJ', models.CharField(max_length=200)),
                ('Num_Registro', models.CharField(max_length=200)),
            ],
        ),
    ]
