# Generated by Django 4.1.7 on 2023-05-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('produto_comercial', models.CharField(max_length=100)),
                ('alvo', models.CharField(max_length=100)),
                ('area_a_tratar', models.FloatField()),
                ('volume_da_calda', models.FloatField()),
                ('intervalo_de_seguranca', models.IntegerField()),
                ('modalidade_aplicacao', models.CharField(max_length=100)),
                ('equipamento_aplicacao', models.CharField(max_length=100)),
                ('quantidade_a_adquirir', models.IntegerField()),
                ('n_aplicacoes', models.IntegerField()),
                ('epoca_aplicacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Precaucao_orientacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrecaucaoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('local', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='respons_tec',
            name='CNPJ',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='respons_tec',
            name='Num_Registro',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiq.propriedade')),
            ],
        ),
    ]
