# Generated by Django 4.1.7 on 2023-05-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0002_diagnostico_precaucao_orientacoes_precaucaouso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipamentos_epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_equip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='local_devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_dev', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='orientacoes_mip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_mip', models.TextField()),
            ],
        ),
    ]
