# Generated by Django 4.1.7 on 2023-05-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0003_equipamentos_epi_local_devolucao_orientacoes_mip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='equipamentos_epi',
            new_name='equipamentos_protecao',
        ),
        migrations.RenameModel(
            old_name='Precaucao_orientacoes',
            new_name='orientacao_mip',
        ),
        migrations.RenameModel(
            old_name='orientacoes_mip',
            new_name='Precaucao_e_orientacao',
        ),
        migrations.RenameModel(
            old_name='respons_tec',
            new_name='Responsavel_Tecnico',
        ),
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'verbose_name_plural': 'Diagnosticos'},
        ),
        migrations.AlterModelOptions(
            name='equipamentos_protecao',
            options={'verbose_name_plural': 'Equipamentos de Protecao Individual'},
        ),
        migrations.AlterModelOptions(
            name='local_devolucao',
            options={'verbose_name_plural': 'Locais de Devolucao'},
        ),
        migrations.AlterModelOptions(
            name='orientacao_mip',
            options={'verbose_name_plural': 'Orientacoes MIP'},
        ),
        migrations.AlterModelOptions(
            name='precaucao_e_orientacao',
            options={'verbose_name_plural': 'Precaucoes e Orientacoes'},
        ),
        migrations.AlterModelOptions(
            name='precaucaouso',
            options={'verbose_name_plural': 'Precaucoes de Uso'},
        ),
        migrations.AlterModelOptions(
            name='produtorrural',
            options={'verbose_name_plural': 'Produtores Rurais'},
        ),
        migrations.AlterModelOptions(
            name='propriedade',
            options={'verbose_name_plural': 'Propriedades'},
        ),
        migrations.AlterModelOptions(
            name='responsavel_tecnico',
            options={'verbose_name_plural': 'Responsaveis Tecnicos'},
        ),
        migrations.RenameField(
            model_name='orientacao_mip',
            old_name='texto',
            new_name='texto_mip',
        ),
        migrations.RenameField(
            model_name='precaucao_e_orientacao',
            old_name='texto_mip',
            new_name='texto',
        ),
    ]
