# Generated by Django 4.1.7 on 2023-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0004_rename_equipamentos_epi_equipamentos_protecao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='area_a_tratar',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='epoca_aplicacao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='intervalo_de_seguranca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='volume_da_calda',
            field=models.CharField(max_length=50),
        ),
    ]
