# Generated by Django 4.1.7 on 2023-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0005_alter_diagnostico_area_a_tratar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
