# Generated by Django 4.1.7 on 2023-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0007_alter_propriedade_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel_tecnico',
            name='CNPJ',
            field=models.CharField(max_length=14),
        ),
    ]
