# Generated by Django 4.1.7 on 2023-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0010_alter_precaucao_e_orientacao_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precaucao_e_orientacao',
            name='texto',
            field=models.TextField(),
        ),
    ]
