# Generated by Django 4.1.7 on 2023-05-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0011_alter_precaucao_e_orientacao_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='equipamentos_protecao',
        ),
        migrations.DeleteModel(
            name='local_devolucao',
        ),
        migrations.DeleteModel(
            name='orientacao_mip',
        ),
        migrations.DeleteModel(
            name='Precaucao_e_orientacao',
        ),
        migrations.DeleteModel(
            name='PrecaucaoUso',
        ),
    ]
