# Generated by Django 4.1.7 on 2023-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0012_delete_equipamentos_protecao_delete_local_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='nomefazenda',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
