# Generated by Django 4.1.7 on 2023-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0013_propriedade_nomefazenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='descricao',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='nomefazenda',
            field=models.CharField(max_length=100),
        ),
    ]
