# Generated by Django 4.1.7 on 2023-05-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiq', '0014_alter_propriedade_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='nomefazenda',
            field=models.CharField(max_length=30),
        ),
    ]
